### ISSUE TITLE
PREMIUM POINT A ACCOUNTING - DOCUMENTATION

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT-ACE-ACCOUNTING#1]
ARC,

Do the below

1.TAKE SCREEN SHOT OF K ACCOUTING
2.LEARN K ACCOUTING AND PREPARE DOCUMENTATION
3.SAVE IN G DRIVE

**Comment by Archana20** [comment]
https://drive.google.com/drive/folders/0B_f0d7mdbV_UfndhdkNmcGZHVHNOcmpNZTFSaWVWMFFfWHN1em1mLUsyWnY2cnV2LWVTUVU
